keys:
  - &user_del age1mlyjps56fpyd053xc2h2m4pu6946y6dtkrr4nkl6lg09tg37jp2sjtx2pj
  - &host_kusanagi age1pm634jg07scfdvqez9rx3zjzfzd4252grjd2005v52fm8jkrgu8qk7kczf

creation_rules:
  - path_regex: ^hosts/_/sops.yaml$
    key_groups:
      - age:
        - *user_del
        - *host_kusanagi
