ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]
:toc:

= https://nixos.org/[NixOS] installation media

The installation media only targets https://uefi.org/[UEFI] compatible `x86_64-linux` hosts for now.
The build of the installation media image is https://nixos.wiki/wiki/Flakes[Flake based].
You will need to https://nixos.wiki/wiki/Flakes#Enable_flakes[enable flakes] for this to work.

All development environment constraints should be guaranteed by the provided `nix-shell` environment.
Issue `nix-shell` or `nix-shell --pure` on the command line to start this environment. +
This shell will be called the *NIM shell* thereafter (_NIM_ stands for _Nixos Installation Media_).

NOTE: Unless stated otherwise, all relative paths (in particular starting with `./`) assume that the current working directory is the project path.

== Building the image

In order to build the installation media image, issue `nimBuild` in the NIM shell. +
The resulting ISO image will be available in `./result/iso`.

NOTE: Use the https://nixos.org/manual/nixos/stable/#sec-obtaining[standard NixOS installation media creation procedures] to obtain a physical installation media.

== Install procedure

NOTE: The following install procedure is targeted at new hosts with no existing NixOS configuration to apply.

Boot the target on the installation media.
Once the boot sequence is complete and the command prompt is available, enter the following commands *on the target*:

[,sh]
----
sudo setupStorage <block device>
sudo generateConfiguration
sudo nixos-install
sudo reboot
----

[NOTE]
====
`<block device>` is the device file pointing to the storage where to install the new NixOS operating system.

It should be `/dev/vda` when testing the installation media image with `nimTest` (see <<Testing>>).
====

== The `setupStorage` command

The goal of the `setupStorage` command is to ensure the following layout on a block device:

. `boot` as the FAT32 partition used by UEFI
. `pv` as the https://gitlab.com/cryptsetup/cryptsetup[LUKS] encrypted device that contains https://tldp.org/HOWTO/LVM-HOWTO/pv.html[a LVM physical volume] which will be part of https://tldp.org/HOWTO/LVM-HOWTO/vg.html[a volume group] named `vg` containing:
** https://tldp.org/HOWTO/LVM-HOWTO/lv.html[a logical volume] named `swap` holding the swap space
** a logical volume named `system` containing a https://btrfs.wiki.kernel.org[Btrfs] filesystem separated in subvolumes:
*** `root` as the root filesystem
*** `home` as the users home directories
*** `nix` as the operating system's https://nixos.wiki/wiki/Nix_package_manager#Nix_store[Nix store]

The only argument required by the command is the block device on which to install the filesystems layout.
After a few verifications, `setupStorage` will ask the following questions:

[source]
----
Enter passphrase for <path of pv device>:
Enter passphrase for /dev/disk/by-label/pv:
----

NOTE: `<path of pv device>` is the second partition on the device provided as an argument to `setupStorage`.

The first password asked is the one used by LUKS to encrypt the `pv` device. +
The second password asked must be *the same* as the first one as it is used by LUKS to open the `pv` device (`/dev/disk/by-label/pv` is in fact a symbolic link to `<path of pv device>`).

Asking the same password twice offers the additional guarantee that no password misspell occurred.

NOTE: In case of a password mismatch, simply issue the `setupStorage` command again to start over.

== The `generateConfiguration` command

Usually having https://datatracker.ietf.org/doc/html/rfc4122[UUIDs] in the `hardware-configuration.nix` file is not an issue until this file is kept in a git repository for reuse.
The goal of the `generateConfiguration` command is to avoid identifying the target's devices in the `/mnt/etc/nixos/hardware-configuration.nix` file with UUIDs.

As the `setupStorage` command  ensures that all devices are accessible through labels, `generateConfiguration` will simply:

. generate the target NixOS configuration with `nixos-generate-config --root /mnt`
. replace all UUIDs generated by `nixos-generate-config` with their corresponding labels

Once the target is successfully deployed, the `hardware-configuration.nix` file can be kept in configuration in a repository for future use (flake deployment for instance).

NOTE: `generateConfiguration` will also ensure that LUKS opens `/dev/disk/by-label/pv` on boot to work around https://github.com/NixOS/nixpkgs/issues/136755[this issue].

== Testing

In order to test the installation media image, issue `nimTest` in the NIM shell (https://www.qemu.org/[QEMU] with https://www.linux-kvm.org/page/Main_Page[KVM] is needed).
The test VM uses https://www.tianocore.org/[TianoCore UEFI implementation] as the installation media is primarily targeted at systems supporting UEFI.

Once the QEMU virtual machine has started, it will boot:

* either on the installation media if no successful install occurred previously
* or on a previously successfully installed NixOS system (to discard it simply issue `rm ./disk.qcow2` in a command shell)

If the installation media has started, issue the commands from the <<Install procedure>> section *on the virtual machine console*.

WARNING: Do *NOT* use these commands on your current host shell, as they may mess up your host operating system if it is NixOS based.

== Mounting the test VM filesystems

In order to mount the test VM filesystems on the development host, issue the following command in a NIM shell:

[,sh]
----
sudo nimMount <mountpoint>
----

Where `<mountpoint>` must be a previously created directory.

In order to later unmount the test VM filesystems, issue the following command in a NIM shell:

[,sh]
----
sudo nimUmount <mountpoint>
----

== Roadmap

* [x] Initial extensible ISO image (implemented by the initial revision)
* [x] Tooling to prepare the local storage (implemented by setupStorage)
* [x] Tooling to install NixOS (nothing to do, standard NixOS install simply works)
* [x] Tooling to make `hardware-configuration.nix` more generic
* [x] Tooling to mount test filesystems on the host
* [ ] Tooling to install the NixOS configuration from a flake on a Git server with requirements to define; +
  `nixos-install` has a `--flake` option
* [x] Add a `shell.nix` file to ensure project's requirements with `nix-shell`
* [x] Ensure hibernate is possible
* [ ] Optionally replace LUKS password by a https://fidoalliance.org/fido2/[FIDO2] compatible dongle

== Inspiration and prior art

Many thanks to https://github.com/wiltaylor[Wil Taylor] for his https://www.youtube.com/playlist?list=PL-saUBvIJzOkjAw_vOac75v-x6EzNzZq-[marvellous introduction to the Nix world]. +
His https://github.com/wiltaylor/nix-iso[nix-iso] project is a wonderful starting point.

I also digged into the following articles:

* https://nixos.wiki/wiki/Creating_a_NixOS_live_CD[NixOS Wiki's _Creating a NixOS live CD_]
* https://nix.dev/tutorials/building-bootable-iso-image[nix.dev's _Building a bootable ISO image_]
* https://hoverbear.org/blog/nix-flake-live-media/[Ana Hobden's _Custom live media with Nix flakes_]
* https://nixos.mayflower.consulting/blog/2018/09/11/custom-images/[Mayflower's _Building Customised NixOS Images_]
